export { default as withStyled } from './hoc'
export { default as Home } from './Home'
export { default as Layout } from './Layout'
export { default as Login } from './Login'
export { default as Register } from './Register'
